"""migracion_final_completa

Revision ID: 110088634e60
Revises: 7a4d6e6d5a3b
Create Date: 2026-05-22 03:13:59.062881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '110088634e60'
down_revision: Union[str, None] = '7a4d6e6d5a3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planes_suscripcion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('costo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duracion_dias', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_planes_suscripcion_id'), 'planes_suscripcion', ['id'], unique=False)
    op.create_table('productos_tienda',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock_actual', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productos_tienda_id'), 'productos_tienda', ['id'], unique=False)
    op.create_table('control_accesos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora_entrada', sa.DateTime(), nullable=True),
    sa.Column('acceso_permitido', sa.Boolean(), nullable=True),
    sa.Column('observaciones', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_control_accesos_id'), 'control_accesos', ['id'], unique=False)
    op.create_table('evaluaciones_biometricas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('entrenador_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('peso_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('estatura_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('porcentaje_grasa', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('observaciones', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['entrenador_id'], ['entrenadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluaciones_biometricas_id'), 'evaluaciones_biometricas', ['id'], unique=False)
    op.create_table('membresias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['planes_suscripcion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_membresias_id'), 'membresias', ['id'], unique=False)
    op.create_table('ventas_tienda',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('fecha_venta', sa.DateTime(), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('metodo_pago', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ventas_tienda_id'), 'ventas_tienda', ['id'], unique=False)
    op.create_table('detalle_ventas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario_aplicado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos_tienda.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas_tienda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalle_ventas_id'), 'detalle_ventas', ['id'], unique=False)
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('membresia_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(), nullable=True),
    sa.Column('metodo_pago', sa.String(length=50), nullable=False),
    sa.Column('referencia_externa', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['membresia_id'], ['membresias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagos_id'), 'pagos', ['id'], unique=False)
    op.alter_column('disciplinas', 'nombre',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('disciplinas', 'descripcion',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.add_column('maquinas', sa.Column('descripcion_tecnica', sa.String(length=255), nullable=True))
    op.add_column('maquinas', sa.Column('estado_operativo', sa.String(length=30), nullable=True))
    op.add_column('maquinas', sa.Column('fecha_adquisicion', sa.Date(), nullable=True))
    op.add_column('maquinas', sa.Column('ultima_revision', sa.Date(), nullable=True))
    op.alter_column('maquinas', 'codigo_serial',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index('ix_maquinas_codigo_serial', table_name='maquinas')
    op.create_unique_constraint(None, 'maquinas', ['codigo_serial'])
    op.drop_column('maquinas', 'estado')
    op.add_column('reservas', sa.Column('fecha_reserva', sa.DateTime(), nullable=True))
    op.add_column('reservas', sa.Column('asistio', sa.Boolean(), nullable=True))
    op.drop_constraint('reservas_cliente_id_fkey', 'reservas', type_='foreignkey')
    op.create_foreign_key(None, 'reservas', 'clientes', ['cliente_id'], ['id'])
    op.add_column('tickets_mantenimiento', sa.Column('fecha_resolucion', sa.DateTime(), nullable=True))
    op.add_column('tickets_mantenimiento', sa.Column('costo_reparacion', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('tickets_mantenimiento', sa.Column('estado_ticket', sa.String(length=20), nullable=True))
    op.drop_column('tickets_mantenimiento', 'estado')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets_mantenimiento', sa.Column('estado', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('tickets_mantenimiento', 'estado_ticket')
    op.drop_column('tickets_mantenimiento', 'costo_reparacion')
    op.drop_column('tickets_mantenimiento', 'fecha_resolucion')
    op.drop_constraint(None, 'reservas', type_='foreignkey')
    op.create_foreign_key('reservas_cliente_id_fkey', 'reservas', 'usuarios', ['cliente_id'], ['id'])
    op.drop_column('reservas', 'asistio')
    op.drop_column('reservas', 'fecha_reserva')
    op.add_column('maquinas', sa.Column('estado', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'maquinas', type_='unique')
    op.create_index('ix_maquinas_codigo_serial', 'maquinas', ['codigo_serial'], unique=True)
    op.alter_column('maquinas', 'codigo_serial',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('maquinas', 'ultima_revision')
    op.drop_column('maquinas', 'fecha_adquisicion')
    op.drop_column('maquinas', 'estado_operativo')
    op.drop_column('maquinas', 'descripcion_tecnica')
    op.alter_column('disciplinas', 'descripcion',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('disciplinas', 'nombre',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_pagos_id'), table_name='pagos')
    op.drop_table('pagos')
    op.drop_index(op.f('ix_detalle_ventas_id'), table_name='detalle_ventas')
    op.drop_table('detalle_ventas')
    op.drop_index(op.f('ix_ventas_tienda_id'), table_name='ventas_tienda')
    op.drop_table('ventas_tienda')
    op.drop_index(op.f('ix_membresias_id'), table_name='membresias')
    op.drop_table('membresias')
    op.drop_index(op.f('ix_evaluaciones_biometricas_id'), table_name='evaluaciones_biometricas')
    op.drop_table('evaluaciones_biometricas')
    op.drop_index(op.f('ix_control_accesos_id'), table_name='control_accesos')
    op.drop_table('control_accesos')
    op.drop_index(op.f('ix_productos_tienda_id'), table_name='productos_tienda')
    op.drop_table('productos_tienda')
    op.drop_index(op.f('ix_planes_suscripcion_id'), table_name='planes_suscripcion')
    op.drop_table('planes_suscripcion')
    # ### end Alembic commands ###
