"""Update maquina columns

Revision ID: b604638d0ef8
Revises: 
Create Date: 2026-05-19 04:14:17.386361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b604638d0ef8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maquinas', sa.Column('codigo_serial', sa.String(length=50), nullable=False))
    op.add_column('maquinas', sa.Column('estado', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_maquinas_codigo_serial'), 'maquinas', ['codigo_serial'], unique=True)
    op.drop_column('maquinas', 'descripcion_tecnica')
    op.drop_column('maquinas', 'created_at')
    op.drop_column('maquinas', 'fecha_adquisicion')
    op.drop_column('maquinas', 'updated_at')
    op.drop_column('maquinas', 'estado_operativo')
    op.drop_column('maquinas', 'ultima_revision')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maquinas', sa.Column('ultima_revision', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('maquinas', sa.Column('estado_operativo', postgresql.ENUM('activa', 'mantenimiento', 'fuera_servicio', name='estadomaquina'), autoincrement=False, nullable=False))
    op.add_column('maquinas', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('maquinas', sa.Column('fecha_adquisicion', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('maquinas', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('maquinas', sa.Column('descripcion_tecnica', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_maquinas_codigo_serial'), table_name='maquinas')
    op.drop_column('maquinas', 'estado')
    op.drop_column('maquinas', 'codigo_serial')
    # ### end Alembic commands ###
